# Generated by Django 2.1.5 on 2019-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='proShop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('head_pro', models.CharField(max_length=50)),
                ('assistant_pro', models.CharField(max_length=10)),
                ('shop_adress', models.CharField(max_length=50)),
                ('shop_phone', models.CharField(max_length=10)),
                ('pga_number', models.IntegerField(max_length=10)),
                ('insrt_timestamp', models.DateField(auto_now_add=True)),
                ('chnge_timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
