# Generated by Django 2.1.5 on 2019-02-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_proshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='proshop',
            name='shop_phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
