# Generated by Django 2.1.5 on 2019-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190217_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isBuyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isPlayer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isShop',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[(1, 'admin'), (2, 'player'), (3, 'shop'), (2, 'buyer')], default=1, max_length=6),
        ),
    ]
