# Generated by Django 2.1.5 on 2019-02-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190217_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proshop',
            name='pga_number',
            field=models.IntegerField(),
        ),
    ]
