# Generated by Django 2.1.5 on 2019-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190217_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'player'), (3, 'shop'), (4, 'buyer')], default=1),
        ),
    ]
