# Generated by Django 2.1.5 on 2019-05-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190430_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
