# Generated by Django 2.1.5 on 2019-05-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_player_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pin',
            field=models.CharField(default='0000', max_length=128),
        ),
    ]
