# Generated by Django 2.1.5 on 2019-02-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_auto_20190217_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won', models.DecimalField(decimal_places=2, max_digits=11)),
                ('position', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('players', models.ManyToManyField(through='tournament.playerResults', to='users.player')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.proShop')),
            ],
        ),
        migrations.AddField(
            model_name='playerresults',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
