# Generated by Django 2.1.5 on 2019-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_players',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
