# Generated by Django 2.1.5 on 2019-03-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190227_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresults',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentPlayer', to='users.player'),
        ),
        migrations.AlterField(
            model_name='playerresults',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentSet', to='tournament.tournament'),
        ),
    ]
