# Generated by Django 2.1.5 on 2019-03-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190301_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresults',
            name='amount_won',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='playerresults',
            name='position',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
