# Generated by Django 2.1.5 on 2019-03-03 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
