# Generated by Django 2.1.5 on 2019-03-19 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_playerresults_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerresults',
            options={'verbose_name_plural': 'playerResults'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopTournament', to='users.proShop'),
        ),
    ]
