# Generated by Django 2.1.5 on 2019-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20190318_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
