# Generated by Django 2.1.5 on 2019-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_prize_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='active',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'abandoned'), (3, 'in_progress'), (4, 'complete')], default=1),
        ),
    ]
