# Generated by Django 2.1.5 on 2019-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_auto_20190413_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresults',
            name='flight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Flight 1'), (2, 'Flight 2'), (3, 'Flight 3'), (4, 'Flight 4'), (5, 'Flight 5'), (6, 'Flight 6'), (7, 'Flight 7'), (8, 'Flight 8'), (9, 'Flight 9'), (10, 'Flight 10'), (11, 'Senior'), (12, 'Women'), (13, 'Junior'), (14, 'Men')], default=1),
        ),
    ]
