# Generated by Django 2.1.5 on 2019-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20190502_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresults',
            name='flight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Senior'), (2, 'Women'), (3, 'Junior'), (4, 'Men')], default=1),
        ),
    ]
