# Generated by Django 2.1.5 on 2019-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20190508_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresults',
            name='division',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Senior'), (2, 'Women'), (3, 'Junior'), (4, 'Men')], default=1),
        ),
        migrations.AlterField(
            model_name='playerresults',
            name='flight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Flight 1'), (2, 'Flight 2'), (3, 'Flight 3'), (4, 'Flight 4'), (5, 'Flight 5'), (6, 'Flight 6'), (7, 'Flight 7'), (8, 'Flight 8'), (9, 'Flight 9'), (10, 'Flight 10')], default=1),
        ),
    ]
