# Generated by Django 2.1.5 on 2019-06-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_auto_20190625_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pga_event',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='pga_event',
            name='host_shop',
        ),
        migrations.RemoveField(
            model_name='pga_event',
            name='players',
        ),
        migrations.RemoveField(
            model_name='results',
            name='PGA_Event',
        ),
        migrations.RemoveField(
            model_name='results',
            name='player',
        ),
        migrations.DeleteModel(
            name='PGA_Event',
        ),
        migrations.DeleteModel(
            name='results',
        ),
    ]
