# Generated by Django 2.1.5 on 2019-06-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20190510_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGA_Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('number_of_players', models.PositiveIntegerField(default=0, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('event_date', models.DateField()),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'abandoned'), (3, 'in_progress'), (4, 'complete')], default=1)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section', to='users.execUser')),
                ('host_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='users.proShop')),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('flight', models.PositiveSmallIntegerField(choices=[(1, 'Flight 1'), (2, 'Flight 2'), (3, 'Flight 3'), (4, 'Flight 4'), (5, 'Flight 5'), (6, 'Flight 6'), (7, 'Flight 7'), (8, 'Flight 8'), (9, 'Flight 9'), (10, 'Flight 10')], default=1)),
                ('division', models.PositiveSmallIntegerField(choices=[(1, 'Senior'), (2, 'Women'), (3, 'Junior'), (4, 'Men')], default=1)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('PGA_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventSet', to='pga_events.PGA_Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventPlayer', to='users.player')),
            ],
        ),
        migrations.AddField(
            model_name='pga_event',
            name='players',
            field=models.ManyToManyField(through='pga_events.results', to='users.player'),
        ),
    ]
