# Generated by Django 2.0.5 on 2019-07-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pga_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pga_event',
            options={'verbose_name_plural': 'PGA Events'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'abandoned'), (3, 'started'), (4, 'complete')], default=1),
        ),
    ]
