# Generated by Django 2.1.5 on 2019-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('account_created', models.DateField(auto_now_add=True)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'player'), (2, 'shop'), (3, 'buyer')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('source_account', models.PositiveIntegerField()),
                ('destination_account', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('transaction_reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
