# Generated by Django 2.1.5 on 2019-04-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190327_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='credits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('date_assigned', models.DateField(auto_now=True)),
                ('expiration_date', models.DateField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountCredits', to='accounts.account')),
            ],
        ),
    ]
