# Generated by Django 2.1.5 on 2019-04-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='myCredits', to='accounts.account'),
        ),
    ]
