# Generated by Django 2.1.5 on 2019-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credits_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Expiring'), (3, 'Expired')], default=1),
        ),
    ]
