# Generated by Django 2.1.5 on 2019-05-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_credits_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'verbose_name_plural': 'Credits'},
        ),
    ]
