# Generated by Django 2.1.5 on 2019-05-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190430_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('BillingEventID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'awaiting_approval'), (2, 'unnapproved'), (3, 'approved')], default=1)),
                ('request_ts', models.DateField(auto_now_add=True)),
                ('update_ts', models.DateField(auto_now=True)),
                ('player_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerBillingEvent', to='accounts.account')),
                ('shop_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopBillingEvents', to='accounts.account')),
            ],
        ),
    ]
