# Generated by Django 2.1.5 on 2019-05-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_billingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='owner',
            field=models.ForeignKey(default=106, on_delete=django.db.models.deletion.CASCADE, related_name='myCredits', to='accounts.account'),
        ),
    ]
