# Generated by Django 2.1.5 on 2019-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190519_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingevent',
            name='auth_attempt_counter',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'awaiting_approval'), (2, 'unnapproved'), (3, 'approved'), (4, 'complete')], default=1),
        ),
    ]
