# Generated by Django 2.1.5 on 2019-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190519_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'awaiting_approval'), (2, 'not approved'), (3, 'approved'), (4, 'complete')], default=1),
        ),
    ]
