# Generated by Django 2.0.5 on 2019-07-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190625_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
