# Generated by Django 2.2.4 on 2019-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'not approved'), (3, 'approved'), (4, 'complete')], default=1),
        ),
    ]
